name:                lasercats
version:             0.0.0.1
github:              "loupgaroublond/lasercats"
license:             Apache
author:              "Yaakov M Nemoy"
maintainer:          "doraemon@yaakovnemoy.com"
copyright:           "2018 Yaakov M Nemoy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/loupgaroublond/lasercats#readme>

dependencies:
- base >= 4.7 && < 5
- text
- amazonka
- amazonka-core
- amazonka-ec2
- lens
- mtl

library:
  source-dirs: src

executables:
  lasercats-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lasercats

tests:
  lasercats-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lasercats
